version: '3'

services:
  pve-qdevice:
    image: patdelapampa/pve-qdevice
    container_name: pve-qdevice
    ports:
      - "2222:22"
      - "5404:5404/udp"
      - "5405:5405/udp"
      - "5406:5406/udp"
    restart: always
    environment:
      - ROOT_PASSWORD=changeMe!    # Set the root user password. If not set, the default password is 'qdevice'
      - TZ=Europe/Paris

    volumes:
      - corosync_data:/etc/corosync

volumes:
  corosync_data:
    name: corosync_data

 